### ISSUE TITLE
Stargate Group Is Empty

### ISSUE THREAD

**Issue by rareweasel** [yearn/yearn-watch#75]
Debug why the Stargate group (Ethereum) is not handling this strategy 

https://etherscan.io/address/0x2b982be433093a80e1801a0dd894994a170a5025#readContract

It is included [here](https://github.com/yearn/yearn-data-analytics/blob/master/src/risk_framework/risks.json).

**Comment by magikadev** [comment]
I found that the strategies included in [criteria.strategies](https://github.com/yearn/yearn-data-analytics/blob/0ee5ee086ec2f2f0a632b005282cac3d2c3c0661/src/risk_framework/risks.json#L526) were not added.

I updated the code to fix it on #77 .

**But [this strategy](https://etherscan.io/address/0x2b982be433093a80e1801a0dd894994a170a5025#readContract) is still not added to the `stargate` group.**

The reason is that the strategy is not existing on strategies lists that we have fetched...

Searched the strategy on `query` page, but nothing shows up...

![image](https://user-images.githubusercontent.com/46446076/175094155-406a31f7-424a-41f9-b67d-c37a3d0781ab.png)

**Comment by Majorfi** [comment]
For some reason, the concerned [vault](https://etherscan.io/address/0x902cF5373317BB3E42660e9F4e85AA21532c0e44) is not available in the [API](https://api.yearn.finance/v1/chains/1/vaults/all), and because of that it's not served on Watch
Will try to see why

**Comment by Majorfi** [comment]
Fixed with last deployment and subgraph update

![Capture d’écran 2022-07-07 à 12 15 48](https://user-images.githubusercontent.com/90963895/177750598-8ec3c7ab-0295-4448-9315-d9fab9d4904a.png)
